### ISSUE TITLE
Issue with 

### ISSUE THREAD

**Issue by neo4u** [ircmaxell/php-cfg#8]
```
root@kali:~/workspace/ast-translator/php-cfg# php demo.php /var/www/html/wordpress/wp-includes/class-wp.php > ../prasanth-tests-cfg/results/class-wp.dot; xdot ../prasanth-tests-cfg/results/class-wp.php.dot
PHP Warning:  array_map(): An error occurred while invoking the map callback in /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php on line 534
PHP Warning:  array_map(): An error occurred while invoking the map callback in /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php on line 534
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Unknown how to deal with scalar type Scalar_EncapsedStringPart' in /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php:1041
Stack trace:
#0 /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php(572): PHPCfg\Parser->parseScalarNode(Object(PhpParser\Node\Scalar\EncapsedStringPart))
#1 [internal function]: PHPCfg\Parser->parseExprNode(Object(PhpParser\Node\Scalar\EncapsedStringPart))
#2 /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php(534): array_map(Array, Array)
#3 /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php(1017): PHPCfg\Parser->parseExprList(Array, 1)
#4 /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php(572): PHPCfg\Parser->parseScalarNode(Object(PhpParser\Node\Scalar\Encapsed))
#5 /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php(672): PHPCfg\Parser->parseExprNode(Object(PhpParser\Node\Scalar\Encapsed))
#6 /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php(658): PHPCfg\Parser->par in /root/workspace/ast-translator/php-cfg/lib/PHPCfg/Parser.php on line 1041
```
Towards testing with wordpress, I have the following issue with the file given at the link below. The function parseScalarNode seems to have an unhandled case of Scalar_EncapsedStringPart and hence results in the runtime exception with notification: ```
default:
                throw new \RuntimeException("Unknown how to deal with scalar type " . $scalar->getType());```

Could you point me to what I can do to fix this?

**Comment by nikic** [comment]
This is a dependency mismatch caused by this library having a dev-master dependency on PHP-Parser. I've now [updated the deps](https://github.com/ircmaxell/php-cfg/commit/e2e6ea7feedb2597259f9587987571393c7d52e8) to depend on `^2.0` and added [support for EncapsedStringPart](https://github.com/ircmaxell/php-cfg/commit/6c6f66ae1c5978783a89af4836b3db47fef16bf3), which IIRC is the only relevant change between those versions.
